### ISSUE TITLE
Attean minimal version

### ISSUE THREAD

**Issue by ppisar** [kjetilk/URI-NamespaceMap#18]
URI-NamespaceMap-1.10 brought a recommended test dependency on Attean.

While metadata declare 0.025 as a minimal version, the test itself at t/types-attean.t:6 requires 0.024. It would be great to align them.

**Comment by kjetilk** [comment]
Yeah, the reason I did that was that types-attean.t will just requires the types that was added in 0.024, but the test suite is seen to fail occasionally due to https://github.com/kasei/attean/issues/141, which is unrelated but fixed in 0.025. 

So, there are basically two different problems, and therefore I used two different versions. I'm certainly open to change it if it causes practical problems though. Why is this problematic?

**Comment by ppisar** [comment]
I though it was an oversight. If it's on purpose, then I'm fine with it.

**Comment by kjetilk** [comment]
OK, good! Admittedly, I didn't quite know what to do, since the code is just feature dependent on 0.024, but I wanted to avoid the test failures that might occur from systems running with 0.024, so I went with 0.025 in the recommendations. Thanks anyway!
